# usage:
# docker run --rm -v $HOME/dev/boki-benchmarks/boki:/boki adjwang/boki-buildenv:dev bash -c "cd /boki && make -j$(nproc)"

FROM ubuntu:focal as builder
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN apt update && \
    apt upgrade -y && \
    apt install -y g++ clang make cmake pkg-config autoconf automake libtool curl unzip

ENV CC=clang
ENV CXX=clang++

# WORKDIR /boki
# COPY . .
# RUN CC=clang CXX=clang++ ./build_deps.sh
# RUN CXX=clang++ make -j $(nproc)